theme: minima                                             
  title: MyKidPix
  description: Automatically finds and backs up photos of your kids from WhatsApp to Google Photos.
  email: support-mykidpix@googlegroups.com
